services:

  ai-bible-quotation:
    image: docker.io/library/eclipse-temurin:21
    container_name: ai-bible-quotation
    working_dir: /AI-Bible-Quotation-App
    restart: always
    volumes:
      - .:/AI-Bible-Quotation-App
      - gradle-cache:/root/.gradle
    command: |
      bash -c "apt-get update && \
               apt-get install -y git curl && \
               curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
               apt-get install -y git-lfs && \
               git config --global --add safe.directory /AI-Bible-Quotation-App && \
               git lfs pull && \
               ./gradlew build --build-cache --no-daemon -x test && \
               chown -R '1000:1000' build && \
               chown -R '1000:1000' lib && \
               java -Djava.library.path=./lib -jar build/libs/*SNAPSHOT.jar"

    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    networks:
      - app


  ai-bible-mongo:
    build:
      dockerfile: mongo/Dockerfile
    container_name: ai-bible-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongo-data:/data/db
    env_file: .env
    networks:
      - app


volumes:
  mongo-data:
  gradle-cache:

networks:
  app:
    name: app
