spring:
  application:
    name: AI Bible Quotation App
  data:
    mongodb:
          uri: mongodb://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_NAME}?authSource=${MONGODB_AUTH}

server:
  port: ${APP_PORT}
  ssl:
    key-store: classpath:certificate/ai.bible.quotation.p12
    key-store-password: ${SSL_PASSWORD}

langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_API_KEY}
      model-name: gemini-2.0-flash-lite-preview-02-05
      log-requests-and-responses: true


