spring:
  application:
    name: AI Bible Quotation App
server:
  port: 8443
  ssl:
    key-store: classpath:certificate/ai.bible.quotation.p12
    key-store-password: D00FDOOF

langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_API_KEY}
      model-name: gemini-2.0-flash-lite-preview-02-05
      log-requests-and-responses: true

